apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8s-config-demo
  name: k8s-config-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-config-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-config-demo
    spec:
      containers:
      - image: k8s-config-demo:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        name: app
        env:
          - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_CONFIG
            value: TRACE
          - name: SPRING_CONFIG_IMPORT
            value: configtree:/workspace/app-config/
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        volumeMounts:
          - name: projected-volume
            mountPath: /workspace/app-config
            readOnly: true
      volumes:
        - name: projected-volume
          projected:
            sources:
              - secret:
                  name: user
                  items:
                    - key: user
                      path: credentials/username
              - secret:
                  name: password
                  items:
                    - key: password
                      path: credentials/password
              - configMap:
                  name: app-config
